export const HomeContent = {
    welcomeH1: "Welcome to our church",
    welcomeH2: "The Almighty Lord Jesus",
    welcomeH3: "Christian Fellowship",
    welcomeButtonCaption: "More",
    welcomeDescription: "United in Faith, Empowered by His Love",
    churchDescription1: "Welcome to The Almighty Lord Jesus Christian Fellowship, where faith is the foundation, and Christ is our cornerstone. Here, we believe in the power of His love to heal, uplift, and transform. As a community of believers, we strive to walk in His light and share His message with the world. Whether you're seeking spiritual growth, fellowship, or a deeper relationship with Christ, you're invited to join us in worship, prayer, and service. Together, we grow stronger in His love, faith, and truth",
    churchTitle2: "WE ARE FAMILY",
    churchDescription2: "At The Almighty Lord Jesus Christian Fellowship, we are more than just a church; we are a family of believers united by our love for Jesus Christ. Our mission is to honor Him through vibrant worship, prayer, and a commitment to spreading His Word. Whether you are new to faith or looking to grow deeper in your walk with Christ, we welcome you to join us as we seek His will and experience His transformative power in our lives. We believe in loving one another as Christ has loved us, and together, we will shine His light in the world.",
    churchTitle3: "EXPERIENCE IT",
    churchDescription3: "The Almighty Lord Jesus Christian Fellowship is a place where faith meets action. We are a community driven by the love of Christ and committed to making a difference in our lives and the lives of others. With open hearts and open arms, we invite you to experience the joy of being part of a church that is centered on His Word and led by His Spirit. Join us in worship, teaching, and fellowship as we grow together in Christ, living out our faith with purpose and passion.",
    contactUsTitle: "Contact us",
    contactUsInputTitle1: "If you have a question feel free to ask!",
    contactUsInputPlaceholder1: "Your email address",
    contactUsInputTitle2: "Message us",
    contactUsInputPlaceholder2: "Enter your message or prayer request",
    contactUsInputTitle3: "Contact Number",
    contactUsInputPlaceholder3: "Enter your contact number",
    contactUsButtonCaption: "Submit",
}